"""Тематические executable-задачи для 108 уроков расширенного курса.

В отличие от прежней ротации шестнадцати базовых упражнений, каждая запись здесь
проверяет инструмент текущего микроурока. ``solution`` хранится только внутри
авторского реестра: публичная карточка получает заготовку, тесты и постепенные
подсказки, но не готовый код.
"""

from __future__ import annotations

from dataclasses import dataclass
from textwrap import indent
from typing import Any


@dataclass(frozen=True)
class TaskBlueprint:
    """Авторская спецификация одной тематической задачи."""

    prompt: str
    starter: str
    solution: str
    cases: tuple[tuple[str, Any], ...]
    plan: str
    near_solution: str
    required_tokens: tuple[str, ...]


def _function(
    signature: str,
    prompt: str,
    body: str,
    cases: tuple[tuple[str, Any], ...],
    plan: str,
    near_solution: str,
    *required_tokens: str,
    prelude: str = "",
) -> TaskBlueprint:
    """Собрать обычную функцию и компилируемую, но незавершённую заготовку."""
    prefix = f"{prelude.rstrip()}\n\n" if prelude.strip() else ""
    starter = f"{prefix}{signature}\n    # Напиши решение здесь\n    return None\n"
    solution = f"{prefix}{signature}\n{indent(body.rstrip(), '    ')}\n"
    return TaskBlueprint(
        prompt=prompt,
        starter=starter,
        solution=solution,
        cases=cases,
        plan=plan,
        near_solution=near_solution,
        required_tokens=required_tokens,
    )


def _raw(
    prompt: str,
    starter: str,
    solution: str,
    cases: tuple[tuple[str, Any], ...],
    plan: str,
    near_solution: str,
    *required_tokens: str,
) -> TaskBlueprint:
    """Собрать задачу с классом, декоратором или несколькими функциями."""
    return TaskBlueprint(
        prompt=prompt,
        starter=starter.rstrip() + "\n",
        solution=solution.rstrip() + "\n",
        cases=cases,
        plan=plan,
        near_solution=near_solution,
        required_tokens=required_tokens,
    )


TOPICAL_TASKS: dict[tuple[str, str], TaskBlueprint] = {
    # 1. Операторы и выражения
    ("operators", "arithmetic"): _function(
        "def subtotal(price, count):",
        "Напиши `subtotal(price, count)`: верни стоимость нескольких одинаковых товаров.",
        "return price * count",
        (("subtotal(120, 3)", 360), ("subtotal(19.5, 2)", 39.0)),
        "Умножь цену одной единицы на количество и верни результат.",
        "Нужная форма: `return price * count`.",
        "*",
    ),
    ("operators", "integer-division"): _function(
        "def leftover_minutes(total_minutes):",
        "Напиши `leftover_minutes(total_minutes)`: верни минуты после выделения полных часов.",
        "return total_minutes % 60",
        (("leftover_minutes(135)", 15), ("leftover_minutes(60)", 0)),
        "Остаток после деления общего числа минут на 60 — это неполный час.",
        "Используй выражение `total_minutes % 60`.",
        "%",
    ),
    ("operators", "booleans"): _function(
        "def can_enter(age, has_ticket):",
        "Напиши `can_enter(age, has_ticket)`: вход разрешён с 18 лет и только с билетом.",
        "return age >= 18 and has_ticket",
        (
            ("can_enter(18, True)", True),
            ("can_enter(25, False)", False),
            ("can_enter(17, True)", False),
        ),
        "Сначала получи два булевых условия, затем соедини их оператором `and`.",
        "Верни `age >= 18 and has_ticket`.",
        "and",
    ),
    ("operators", "floating-point"): _function(
        "def rounded_sum(left, right):",
        "Напиши `rounded_sum(left, right)`: сложи числа и округли результат до двух знаков.",
        "return round(left + right, 2)",
        (("rounded_sum(0.1, 0.2)", 0.3), ("rounded_sum(1.235, 0)", 1.24)),
        "Сначала сложи значения, затем передай сумму и число знаков в `round`.",
        "Форма вызова: `round(left + right, 2)`.",
        "round",
    ),
    # 2. Строки глубже
    ("strings-pro", "indexes"): _function(
        "def inner_code(text):",
        "Напиши `inner_code(text)`: верни символы с индексов 1, 2 и 3.",
        "return text[1:4]",
        (("inner_code('python')", "yth"), ("inner_code('ABCDE')", "BCD")),
        "В срезе правая граница не включается: нужны границы 1 и 4.",
        "Верни `text[1:4]`.",
        "[1:4]",
    ),
    ("strings-pro", "search-replace"): _function(
        "def normalize_decimal(text):",
        "Напиши `normalize_decimal(text)`: замени все запятые десятичными точками.",
        "return text.replace(',', '.')",
        (
            ("normalize_decimal('Цена 10,50')", "Цена 10.50"),
            ("normalize_decimal('1,2,3')", "1.2.3"),
        ),
        "Вызови строковый метод, указав сначала старый, затем новый фрагмент.",
        "Нужный вызов: `text.replace(',', '.')`.",
        ".replace(",
    ),
    ("strings-pro", "split-join"): _function(
        "def join_tags(tags):",
        "Напиши `join_tags(tags)`: соедини список тегов через запятую и пробел.",
        "return ', '.join(tags)",
        (("join_tags(['python', 'api'])", "python, api"), ("join_tags(['solo'])", "solo")),
        "Разделитель вызывает `join`, а список строк передаётся аргументом.",
        "Используй `', '.join(tags)`.",
        ".join(",
    ),
    ("strings-pro", "formatting"): _function(
        "def format_xp(score):",
        "Напиши `format_xp(score)`: выровняй число по правому краю в поле шириной 5 и добавь ` XP`.",
        "return f'{score:>5} XP'",
        (("format_xp(42)", "   42 XP"), ("format_xp(12345)", "12345 XP")),
        "Помести число в f-строку и добавь спецификацию выравнивания после двоеточия.",
        "Формат поля: `{score:>5}`.",
        "f'",
        ":>5",
    ),
    # 3. Кортежи и последовательности
    ("tuples-slices", "tuples"): _function(
        "def make_point(x, y):",
        "Напиши `make_point(x, y)`: верни координаты как двухэлементный кортеж.",
        "return (x, y)",
        (("list(make_point(10, 20))", [10, 20]), ("list(make_point(-1, 5))", [-1, 5])),
        "Собери два значения в круглых скобках и верни их одной последовательностью.",
        "Верни `(x, y)`.",
        "(",
        ",",
    ),
    ("tuples-slices", "unpacking"): _function(
        "def swap_point(point):",
        "Напиши `swap_point(point)`: распакуй пару и верни координаты в обратном порядке списком.",
        "x, y = point\nreturn [y, x]",
        (("swap_point((10, 20))", [20, 10]), ("swap_point(('left', 'right'))", ["right", "left"])),
        "Слева от `=` укажи два имени, затем собери их в обратном порядке.",
        "Сначала `x, y = point`, потом `return [y, x]`.",
        "x, y =",
    ),
    ("tuples-slices", "slices"): _function(
        "def every_second(values):",
        "Напиши `every_second(values)`: верни каждый второй элемент, начиная с первого.",
        "return values[::2]",
        (("every_second([0, 1, 2, 3, 4])", [0, 2, 4]), ("every_second(['a', 'b'])", ["a"])),
        "Оставь обе границы среза пустыми и укажи только шаг 2.",
        "Верни `values[::2]`.",
        "[::2]",
    ),
    ("tuples-slices", "zip-enumerate"): _function(
        "def numbered_names(names):",
        "Напиши `numbered_names(names)`: верни пары `[номер, имя]`, начиная нумерацию с 1.",
        "result = []\nfor index, name in enumerate(names, start=1):\n    result.append([index, name])\nreturn result",
        (("numbered_names(['Аня', 'Лев'])", [[1, "Аня"], [2, "Лев"]]), ("numbered_names([])", [])),
        "Перебирай `enumerate` с `start=1` и преобразуй каждую пару в список.",
        "Используй `for index, name in enumerate(names, start=1)`.",
        "enumerate(",
        "start=1",
    ),
    # 4. Списки в работе
    ("lists-pro", "list-methods"): _function(
        "def add_task(tasks, title):",
        "Напиши `add_task(tasks, title)`: добавь название в конец списка и верни список.",
        "tasks.append(title)\nreturn tasks",
        (("add_task(['код'], 'тесты')", ["код", "тесты"]), ("add_task([], 'старт')", ["старт"])),
        "Измени исходный список методом `append`, затем верни его.",
        "Сначала `tasks.append(title)`, затем `return tasks`.",
        ".append(",
    ),
    ("lists-pro", "sorting"): _function(
        "def descending(scores):",
        "Напиши `descending(scores)`: верни новый список оценок по убыванию.",
        "return sorted(scores, reverse=True)",
        (("descending([3, 1, 5])", [5, 3, 1]), ("descending([])", [])),
        "Используй `sorted`, не меняя исходный список, и включи обратный порядок.",
        "Нужен вызов `sorted(scores, reverse=True)`.",
        "sorted(",
        "reverse=True",
    ),
    ("lists-pro", "stacks-queues"): _function(
        "def take_last(stack):",
        "Напиши `take_last(stack)`: сними и верни последний элемент стека.",
        "return stack.pop()",
        (("take_last(['первая', 'последняя'])", "последняя"), ("take_last([7])", 7)),
        "У стека следующим выходит элемент с конца; `pop()` без индекса делает именно это.",
        "Верни результат `stack.pop()`.",
        ".pop(",
    ),
    ("lists-pro", "mutation"): _function(
        "def remove_negatives(items):",
        "Напиши `remove_negatives(items)`: удали отрицательные числа, безопасно обходя копию списка.",
        "for item in items[:]:\n    if item < 0:\n        items.remove(item)\nreturn items",
        (("remove_negatives([2, -1, -3, 4])", [2, 4]), ("remove_negatives([-1, -2])", [])),
        "Перебирай срез-копию `items[:]`, а удаляй элементы из оригинала.",
        "Цикл начинается `for item in items[:]`, внутри при `item < 0` вызови `remove`.",
        "items[:]",
        ".remove(",
    ),
    # 5. Словари и множества
    ("mappings", "dict-basics"): _function(
        "def display_name(user):",
        "Напиши `display_name(user)`: верни имя или `Гость`, если ключ отсутствует.",
        "return user.get('name', 'Гость')",
        (("display_name({'name': 'Лена'})", "Лена"), ("display_name({})", "Гость")),
        "Метод `get` принимает ключ и запасное значение вторым аргументом.",
        "Верни `user.get('name', 'Гость')`.",
        ".get(",
    ),
    ("mappings", "dict-loops"): _function(
        "def setting_lines(settings):",
        "Напиши `setting_lines(settings)`: верни строки `ключ=значение` в порядке словаря.",
        "lines = []\nfor key, value in settings.items():\n    lines.append(f'{key}={value}')\nreturn lines",
        (
            ("setting_lines({'theme': 'dark', 'size': 2})", ["theme=dark", "size=2"]),
            ("setting_lines({})", []),
        ),
        "Метод `items()` даёт пары; распакуй каждую в `key, value`.",
        "Используй `for key, value in settings.items()`.",
        ".items(",
    ),
    ("mappings", "dict-merge"): _function(
        "def merge_config(defaults, overrides):",
        "Напиши `merge_config(defaults, overrides)`: объедини словари так, чтобы overrides побеждал.",
        "return defaults | overrides",
        (
            (
                "merge_config({'theme': 'light', 'size': 1}, {'theme': 'dark'})",
                {"theme": "dark", "size": 1},
            ),
            ("merge_config({}, {'ready': True})", {"ready": True}),
        ),
        "Оператор `|` создаёт новый словарь; правый словарь заменяет совпавшие ключи.",
        "Верни `defaults | overrides`.",
        "|",
    ),
    ("mappings", "sets"): _function(
        "def shared_skills(left, right):",
        "Напиши `shared_skills(left, right)`: верни отсортированный список общих навыков.",
        "return sorted(set(left) & set(right))",
        (
            ("shared_skills(['python', 'sql'], ['sql', 'git'])", ["sql"]),
            ("shared_skills([], ['python'])", []),
        ),
        "Преобразуй обе коллекции в множества, найди пересечение `&`, затем отсортируй результат.",
        "Форма ядра решения: `set(left) & set(right)`.",
        "set(",
        "&",
    ),
    # 6. Продвинутая логика
    ("flow-advanced", "elif"): _function(
        "def grade(score):",
        "Напиши `grade(score)`: A от 90, B от 70, иначе C.",
        "if score >= 90:\n    return 'A'\nelif score >= 70:\n    return 'B'\nreturn 'C'",
        (("grade(95)", "A"), ("grade(70)", "B"), ("grade(69)", "C")),
        "Проверяй пороги сверху вниз, чтобы высокий балл не попал в более широкую ветку.",
        "После `if score >= 90` используй `elif score >= 70`.",
        "elif",
    ),
    ("flow-advanced", "match"): _function(
        "def command_message(command):",
        "Напиши `command_message(command)` через match: start → `Поехали`, stop → `Стоп`, иначе `Неизвестно`.",
        "match command:\n    case 'start':\n        return 'Поехали'\n    case 'stop':\n        return 'Стоп'\n    case _:\n        return 'Неизвестно'",
        (
            ("command_message('start')", "Поехали"),
            ("command_message('stop')", "Стоп"),
            ("command_message('help')", "Неизвестно"),
        ),
        "Сопоставь значение с двумя строковыми case и заверши веткой `case _`.",
        "Каркас: `match command`, затем `case 'start'`, `case 'stop'`, `case _`.",
        "match ",
        "case ",
    ),
    ("flow-advanced", "break-continue"): _function(
        "def non_negative(values):",
        "Напиши `non_negative(values)`: пропускай отрицательные числа через continue.",
        "result = []\nfor value in values:\n    if value < 0:\n        continue\n    result.append(value)\nreturn result",
        (("non_negative([-2, 0, 3])", [0, 3]), ("non_negative([-1])", [])),
        "Создай результат; при отрицательном значении сразу переходи к следующей итерации.",
        "Внутри цикла: `if value < 0: continue`; добавление идёт после условия.",
        "continue",
    ),
    ("flow-advanced", "loop-else"): _function(
        "def find_position(items, target):",
        "Напиши `find_position(items, target)`: верни индекс найденного элемента, а из else цикла — -1.",
        "for index, item in enumerate(items):\n    if item == target:\n        break\nelse:\n    return -1\nreturn index",
        (("find_position(['a', 'b'], 'b')", 1), ("find_position(['a'], 'x')", -1)),
        "При совпадении сохрани индекс выходом `break`; `else` цикла сработает только без break.",
        "После цикла поставь `else: return -1`, а найденный index верни ниже.",
        "break",
        "else:",
    ),
    # 7. Функции: следующий уровень
    ("functions-pro", "parameters"): _function(
        "def move(x, y):",
        "Напиши `move(x, y)`: верни координаты списком в том же порядке, в котором переданы аргументы.",
        "return [x, y]",
        (("move(3, 7)", [3, 7]), ("move(-1, 0)", [-1, 0])),
        "Позиционные аргументы связываются с параметрами слева направо.",
        "Собери и верни `[x, y]`.",
        "def move(x, y)",
    ),
    ("functions-pro", "defaults"): _function(
        "def greet(name, prefix='Привет'):",
        "Напиши `greet`: с одним аргументом используй `Привет`, со вторым — переданный prefix.",
        "return f'{prefix}, {name}'",
        (("greet('Аня')", "Привет, Аня"), ("greet('Лев', 'Добрый день')", "Добрый день, Лев")),
        "Задай запасной текст прямо в заголовке функции и используй параметр в результате.",
        "Заголовок содержит `prefix='Привет'`, результат — f-строка из prefix и name.",
        "prefix='Привет'",
    ),
    ("functions-pro", "keyword-args"): _raw(
        "Реализуй `open_local()`: вызови готовую `connect` именно с именованными аргументами host и timeout.",
        "def connect(host, timeout):\n    return f'{host}:{timeout}'\n\ndef open_local():\n    # Вызови connect с именованными аргументами\n    return None\n",
        "def connect(host, timeout):\n    return f'{host}:{timeout}'\n\ndef open_local():\n    return connect(host='localhost', timeout=3)\n",
        (("open_local()", "localhost:3"), ("connect(host='server', timeout=9)", "server:9")),
        "В вызове после имени каждого параметра поставь `=`; порядок тогда не определяет смысл.",
        "Верни `connect(host='localhost', timeout=3)`.",
        "host=",
        "timeout=",
    ),
    ("functions-pro", "varargs"): _function(
        "def report(*items, **options):",
        "Напиши `report(*items, **options)`: соедини items через запятую и добавь prefix из options (по умолчанию `Отчёт`).",
        "prefix = options.get('prefix', 'Отчёт')\nreturn f\"{prefix}: {', '.join(items)}\"",
        (
            ("report('код', 'тесты')", "Отчёт: код, тесты"),
            ("report('готово', prefix='Статус')", "Статус: готово"),
        ),
        "Позиционные значения лежат в кортеже items, именованные — в словаре options.",
        "Возьми `options.get('prefix', 'Отчёт')`, затем соедини `items` методом join.",
        "*items",
        "**options",
    ),
    # 8. Области видимости
    ("scope", "legb"): _raw(
        "Допиши `show()`, чтобы локальное имя не меняло одноимённое значение снаружи; верни оба значения списком.",
        "name = 'глобально'\n\ndef show():\n    # Создай локальную переменную name\n    return None\n",
        "name = 'глобально'\n\ndef show():\n    name = 'локально'\n    return [name, globals_name()]\n\ndef globals_name():\n    return name\n",
        (("show()", ["локально", "глобально"]), ("globals_name()", "глобально")),
        "Присваивание внутри функции создаёт локальное имя; отдельная функция прочитает внешнее.",
        "Внутри show задай `name = 'локально'`; внешнее значение читай через готовый помощник.",
        "name = 'локально'",
    ),
    ("scope", "mutable-default"): _function(
        "def add_item(item, bucket=None):",
        "Напиши `add_item(item, bucket=None)`: создавай новый список, только когда bucket равен None.",
        "if bucket is None:\n    bucket = []\nbucket.append(item)\nreturn bucket",
        (("add_item('a')", ["a"]), ("add_item('b', ['a'])", ["a", "b"])),
        "Сначала замени None новым списком, затем добавь элемент в выбранный bucket.",
        "Используй `if bucket is None: bucket = []`, после чего append и return.",
        "bucket=None",
        "is None",
    ),
    ("scope", "closures"): _raw(
        "Напиши `multiplier(n)`, возвращающую вложенную функцию, которая умножает значение на сохранённое n.",
        "def multiplier(n):\n    def apply(value):\n        # Вложенная функция помнит n\n        return None\n    return apply\n",
        "def multiplier(n):\n    def apply(value):\n        return value * n\n    return apply\n",
        (("multiplier(3)(4)", 12), ("multiplier(-2)(5)", -10)),
        "Определи apply внутри multiplier и верни саму функцию без скобок.",
        "В apply верни `value * n`, а снаружи — `return apply`.",
        "def apply",
        "return apply",
    ),
    ("scope", "lambda-key"): _function(
        "def youngest_first(users):",
        "Напиши `youngest_first(users)`: верни новый список словарей, отсортированный по полю age через lambda.",
        "return sorted(users, key=lambda user: user['age'])",
        (
            ("youngest_first([{'age': 30}, {'age': 18}])", [{"age": 18}, {"age": 30}]),
            ("youngest_first([])", []),
        ),
        "Передай в key маленькую функцию, которая для одного user возвращает возраст.",
        "Ключ сортировки: `key=lambda user: user['age']`.",
        "lambda",
        "key=",
    ),
    # 9. Генерация коллекций
    ("comprehensions", "list-comprehension"): _function(
        "def squares(numbers):",
        "Напиши `squares(numbers)` одним list comprehension.",
        "return [number * number for number in numbers]",
        (("squares([1, 2, 3])", [1, 4, 9]), ("squares([])", [])),
        "В начале скобок укажи выражение результата, затем `for` по исходному списку.",
        "Верни `[number * number for number in numbers]`.",
        "[",
        " for ",
    ),
    ("comprehensions", "comprehension-filter"): _function(
        "def even_squares(numbers):",
        "Напиши `even_squares(numbers)`: квадраты только чётных чисел через comprehension с условием.",
        "return [number * number for number in numbers if number % 2 == 0]",
        (("even_squares([1, 2, 3, 4])", [4, 16]), ("even_squares([1, 3])", [])),
        "После части for добавь фильтр `if`; выражение квадрата остаётся в начале.",
        "Форма: `[number * number for number in numbers if number % 2 == 0]`.",
        " for ",
        " if ",
    ),
    ("comprehensions", "dict-comprehension"): _function(
        "def word_lengths(words):",
        "Напиши `word_lengths(words)`: словарь слово → длина через dict comprehension.",
        "return {word: len(word) for word in words}",
        (("word_lengths(['кот', 'python'])", {"кот": 3, "python": 6}), ("word_lengths([])", {})),
        "До for запиши пару `ключ: значение`, а не одно выражение.",
        "Верни `{word: len(word) for word in words}`.",
        "{",
        ":",
        " for ",
    ),
    ("comprehensions", "nested-comprehension"): _function(
        "def all_pairs(xs, ys):",
        "Напиши `all_pairs(xs, ys)`: все комбинации `[x, y]` двумя for внутри comprehension.",
        "return [[x, y] for x in xs for y in ys]",
        (("all_pairs([1, 2], ['a'])", [[1, "a"], [2, "a"]]), ("all_pairs([], [1])", [])),
        "Второй for вложен в первый: для каждого x перебираются все y.",
        "Верни `[[x, y] for x in xs for y in ys]`.",
        " for x ",
        " for y ",
    ),
    # 10. Итераторы и генераторы
    ("iterators", "iterable"): _function(
        "def first_two(values):",
        "Напиши `first_two(values)`: создай итератор и верни первые два значения списком.",
        "iterator = iter(values)\nreturn [next(iterator), next(iterator)]",
        (("first_two([10, 20, 30])", [10, 20]), ("first_two('ab')", ["a", "b"])),
        "Один раз вызови iter, затем дважды next для того же объекта.",
        "Сохрани `iterator = iter(values)` и верни два вызова `next(iterator)`.",
        "iter(",
        "next(",
    ),
    ("iterators", "stop-iteration"): _function(
        "def next_or(iterator, default):",
        "Напиши `next_or(iterator, default)`: верни следующий элемент, а при StopIteration — default.",
        "try:\n    return next(iterator)\nexcept StopIteration:\n    return default",
        (("next_or(iter([7]), 0)", 7), ("next_or(iter([]), 'конец')", "конец")),
        "Перехвати именно сигнал исчерпания итератора вокруг одного вызова next.",
        "Используй `try: return next(iterator)` и `except StopIteration: return default`.",
        "StopIteration",
    ),
    ("iterators", "yield"): _raw(
        "Напиши генератор `count_up(limit)`, который выдаёт числа от 0 до limit - 1.",
        "def count_up(limit):\n    for value in range(limit):\n        # Выдай очередное значение\n        return None\n",
        "def count_up(limit):\n    for value in range(limit):\n        yield value\n",
        (("list(count_up(4))", [0, 1, 2, 3]), ("list(count_up(0))", [])),
        "В генераторе не собирай список: выдавай value на каждой итерации.",
        "Внутри цикла нужна строка `yield value`.",
        "yield",
    ),
    ("iterators", "generator-expression"): _function(
        "def square_total(numbers):",
        "Напиши `square_total(numbers)`: сумма квадратов через генераторное выражение без списка.",
        "return sum(number * number for number in numbers)",
        (("square_total([1, 2, 3])", 14), ("square_total([])", 0)),
        "Передай выражение с for прямо в sum, без квадратных скобок.",
        "Верни `sum(number * number for number in numbers)`.",
        "sum(",
        " for ",
    ),
    # 11. Модули и пакеты
    ("modules", "imports"): _function(
        "def square_root(value):",
        "Импортируй math и напиши `square_root(value)` через `math.sqrt`.",
        "return math.sqrt(value)",
        (("square_root(9)", 3.0), ("square_root(2.25)", 1.5)),
        "Импорт находится до функции; внутри обратись к имени модуля через точку.",
        "После `import math` верни `math.sqrt(value)`.",
        "import math",
        "math.sqrt",
        prelude="import math",
    ),
    ("modules", "main-guard"): _function(
        "def should_start(module_name):",
        "Напиши `should_start(module_name)`: верни True только для имени `__main__` — это логика main guard.",
        "return module_name == '__main__'",
        (("should_start('__main__')", True), ("should_start('service')", False)),
        "Main guard сравнивает служебное имя модуля со строкой `__main__`.",
        "Верни сравнение `module_name == '__main__'`.",
        "__main__",
    ),
    ("modules", "packages"): _function(
        "def import_path(package, module):",
        "Без реального импорта собери точечный путь модуля пакета: `package.module`.",
        "return f'{package}.{module}'",
        (
            ("import_path('app', 'services')", "app.services"),
            ("import_path('shop', 'models')", "shop.models"),
        ),
        "В Python уровни пакета разделяются точками, а не слешами файловой системы.",
        "Верни f-строку `f'{package}.{module}'`.",
        ".",
    ),
    ("modules", "stdlib-imports"): _function(
        "def child_path(folder, filename):",
        "Импортируй Path и напиши `child_path`: соедини части оператором `/`, верни путь в POSIX-виде.",
        "return (Path(folder) / filename).as_posix()",
        (
            ("child_path('notes', 'today.txt')", "notes/today.txt"),
            ("child_path('data', 'items.json')", "data/items.json"),
        ),
        "Создай Path из папки, присоедини имя через `/`, затем получи POSIX-форму методом Path.",
        "Верни `(Path(folder) / filename).as_posix()`.",
        "from pathlib import Path",
        "Path(",
        ".as_posix(",
        prelude="from pathlib import Path",
    ),
    # 12. Файлы и форматы данных
    ("files-data", "pathlib"): _function(
        "def note_path(day):",
        "Напиши `note_path(day)`: собери `notes/<day>.txt` через Path и верни POSIX-строку.",
        "return (Path('notes') / f'{day}.txt').as_posix()",
        (("note_path('today')", "notes/today.txt"), ("note_path('monday')", "notes/monday.txt")),
        "Создай базовый Path, присоедини имя файла оператором `/`.",
        "Собери `Path('notes') / f'{day}.txt'` и вызови `.as_posix()`.",
        "Path(",
        ".as_posix(",
        prelude="from pathlib import Path",
    ),
    ("files-data", "text-files"): _function(
        "def save_and_read(filename, text):",
        "Напиши `save_and_read`: запиши текст в учебный файл UTF-8, затем прочитай и верни его.",
        "with open(filename, 'w', encoding='utf-8') as file:\n    file.write(text)\nwith open(filename, encoding='utf-8') as file:\n    return file.read()",
        (("save_and_read('note.txt', 'Привет')", "Привет"), ("save_and_read('empty.txt', '')", "")),
        "Используй два блока with: первый с режимом w, второй без режима для чтения.",
        "Сначала `open(..., 'w', encoding='utf-8')`, затем `open(..., encoding='utf-8')`.",
        "with open(",
        "encoding='utf-8'",
    ),
    ("files-data", "json"): _function(
        "def json_roundtrip(data):",
        "Импортируй json: сериализуй data с ensure_ascii=False и сразу восстанови объект.",
        "text = json.dumps(data, ensure_ascii=False)\nreturn json.loads(text)",
        (
            ("json_roundtrip({'done': True, 'title': 'Код'})", {"done": True, "title": "Код"}),
            ("json_roundtrip([1, 2])", [1, 2]),
        ),
        "`dumps` превращает объект в текст, `loads` выполняет обратное преобразование.",
        "Сохрани `json.dumps(...)` в text и верни `json.loads(text)`.",
        "json.dumps",
        "json.loads",
        prelude="import json",
    ),
    ("files-data", "csv"): _function(
        "def parse_scores(lines):",
        "Импортируй csv и напиши `parse_scores(lines)`: пропусти заголовок и верни словарь имя → целый балл.",
        "rows = csv.reader(lines)\nnext(rows)\nreturn {name: int(score) for name, score in rows}",
        (
            ("parse_scores(['name,score', 'Аня,10', 'Лев,7'])", {"Аня": 10, "Лев": 7}),
            ("parse_scores(['name,score'])", {}),
        ),
        "csv.reader принимает iterable строк; первая строка — заголовок, её можно снять next.",
        "Создай `rows = csv.reader(lines)`, вызови `next(rows)`, затем собери словарь.",
        "csv.reader",
        prelude="import csv",
    ),
    # 13. Ошибки и отладка
    ("errors-debug", "exception-types"): _function(
        "def parse_integer(text):",
        "Напиши `parse_integer(text)`: верни число, а при ValueError — None.",
        "try:\n    return int(text)\nexcept ValueError:\n    return None",
        (("parse_integer('42')", 42), ("parse_integer('abc')", None)),
        "Оберни преобразование int в try и перехвати конкретный ValueError.",
        "Используй `except ValueError: return None`.",
        "ValueError",
    ),
    ("errors-debug", "raise"): _raw(
        "Реализуй `require_age(age)`, выбрасывающую ValueError для отрицательного возраста; helper вернёт текст ошибки.",
        "def require_age(age):\n    # Проверь age и при ошибке используй raise\n    return age\n\ndef age_result(age):\n    try:\n        return require_age(age)\n    except ValueError as error:\n        return f'{error}'\n",
        "def require_age(age):\n    if age < 0:\n        raise ValueError('Возраст не может быть отрицательным')\n    return age\n\ndef age_result(age):\n    try:\n        return require_age(age)\n    except ValueError as error:\n        return f'{error}'\n",
        (("age_result(18)", 18), ("age_result(-1)", "Возраст не может быть отрицательным")),
        "Проверь недопустимое значение до обычного return и создай ValueError с понятным сообщением.",
        "В ветке `if age < 0` напиши `raise ValueError('Возраст не может быть отрицательным')`.",
        "raise ValueError",
    ),
    ("errors-debug", "finally"): _function(
        "def parse_with_log(text):",
        "Напиши `parse_with_log(text)`: верни `[значение, события]`; при ошибке значение 0, а `Готово` добавляется в finally.",
        "events = []\ntry:\n    value = int(text)\nexcept ValueError:\n    value = 0\nfinally:\n    events.append('Готово')\nreturn [value, events]",
        (("parse_with_log('7')", [7, ["Готово"]]), ("parse_with_log('нет')", [0, ["Готово"]])),
        "Создай events до try; finally должен выполняться и после успеха, и после except.",
        "Добавление `events.append('Готово')` помести именно в finally.",
        "finally:",
    ),
    ("errors-debug", "debugging"): _function(
        "def debug_value(value):",
        "Напиши `debug_value(value)` через самодокументирующую f-строку `{value=}`.",
        "return f'{value=}'",
        (("debug_value(7)", "value=7"), ("debug_value('код')", "value='код'")),
        "Знак `=` внутри фигурных скобок выводит одновременно имя выражения и repr значения.",
        "Верни `f'{value=}'`.",
        "{value=}",
    ),
    # 14. ООП: проектирование
    ("oop-design", "init"): _raw(
        "Создай класс Task: `__init__(self, title)` должен сохранить title в атрибуте экземпляра.",
        "class Task:\n    def __init__(self, title):\n        # Сохрани title в self\n        self.title = None\n",
        "class Task:\n    def __init__(self, title):\n        self.title = title\n",
        (("Task('Тесты').title", "Тесты"), ("Task('').title", "")),
        "В конструкторе левее `=` должен быть атрибут конкретного объекта `self.title`.",
        "Строка конструктора: `self.title = title`.",
        "__init__",
        "self.title",
    ),
    ("oop-design", "repr-str"): _raw(
        "Создай Task с title и `__repr__`, возвращающим строку вида `Task('Код')`.",
        "class Task:\n    def __init__(self, title):\n        self.title = title\n\n    def __repr__(self):\n        # Верни однозначное представление\n        return ''\n",
        "class Task:\n    def __init__(self, title):\n        self.title = title\n\n    def __repr__(self):\n        return f'Task({self.title!r})'\n",
        (("repr(Task('Код'))", "Task('Код')"), ("repr(Task('A'))", "Task('A')")),
        "Используй `!r`, чтобы строковое значение title получило кавычки как в коде.",
        "Верни `f'Task({self.title!r})'`.",
        "__repr__",
        "!r",
    ),
    ("oop-design", "class-instance"): _raw(
        "Создай Task с общим атрибутом класса `default_priority='normal'` и личным title.",
        "class Task:\n    # Добавь общий атрибут класса\n\n    def __init__(self, title):\n        # Добавь атрибут экземпляра\n        return None\n",
        "class Task:\n    default_priority = 'normal'\n\n    def __init__(self, title):\n        self.title = title\n",
        (("Task('Код').default_priority", "normal"), ("Task('Тесты').title", "Тесты")),
        "Общее значение объяви в теле класса, а уникальное — через self внутри конструктора.",
        "В классе `default_priority = 'normal'`; в __init__ — `self.title = title`.",
        "default_priority",
        "self.title",
    ),
    ("oop-design", "composition"): _raw(
        "Реализуй композицию: Project хранит список Task, а `add(title)` создаёт и добавляет задачу; titles возвращает названия.",
        "class Task:\n    def __init__(self, title):\n        self.title = title\n\nclass Project:\n    def __init__(self):\n        self.tasks = []\n\n    def add(self, title):\n        # Создай Task и добавь в проект\n        return None\n\n    def titles(self):\n        return [task.title for task in self.tasks]\n\ndef project_titles(titles):\n    project = Project()\n    for title in titles:\n        project.add(title)\n    return project.titles()\n",
        "class Task:\n    def __init__(self, title):\n        self.title = title\n\nclass Project:\n    def __init__(self):\n        self.tasks = []\n\n    def add(self, title):\n        self.tasks.append(Task(title))\n\n    def titles(self):\n        return [task.title for task in self.tasks]\n\ndef project_titles(titles):\n    project = Project()\n    for title in titles:\n        project.add(title)\n    return project.titles()\n",
        (("project_titles(['Код', 'Тесты'])", ["Код", "Тесты"]), ("project_titles([])", [])),
        "Project не наследуется от Task: он создаёт объекты Task и хранит их внутри.",
        "В add вызови `self.tasks.append(Task(title))`.",
        "Task(title)",
        ".append(",
    ),
    # 15. ООП: расширение
    ("oop-advanced", "inheritance"): _raw(
        "Создай TimedTask(Task): вызови super().__init__(title), затем сохрани minutes.",
        "class Task:\n    def __init__(self, title):\n        self.title = title\n\nclass TimedTask(Task):\n    def __init__(self, title, minutes):\n        # Инициализируй базовую часть и minutes\n        return None\n",
        "class Task:\n    def __init__(self, title):\n        self.title = title\n\nclass TimedTask(Task):\n    def __init__(self, title, minutes):\n        super().__init__(title)\n        self.minutes = minutes\n",
        (("TimedTask('Код', 25).title", "Код"), ("TimedTask('Тесты', 15).minutes", 15)),
        "Конструктор подкласса сначала делегирует общую настройку базовому классу.",
        "Начни с `super().__init__(title)`, затем `self.minutes = minutes`.",
        "super().__init__",
    ),
    ("oop-advanced", "properties"): _raw(
        "Создай Progress с done/total и read-only свойством ratio; при total=0 верни 0.",
        "class Progress:\n    def __init__(self, done, total):\n        self.done = done\n        self.total = total\n\n    @property\n    def ratio(self):\n        # Вычисли долю\n        return None\n",
        "class Progress:\n    def __init__(self, done, total):\n        self.done = done\n        self.total = total\n\n    @property\n    def ratio(self):\n        if self.total == 0:\n            return 0\n        return self.done / self.total\n",
        (("Progress(3, 4).ratio", 0.75), ("Progress(0, 0).ratio", 0)),
        "Декоратор позволяет читать метод без скобок; внутри защити деление на ноль.",
        "Над методом поставь `@property`; верни 0 при total == 0, иначе done / total.",
        "@property",
    ),
    ("oop-advanced", "protocols"): _raw(
        "Создай Countdown(start), поддерживающий `for` через `__iter__`; он выдаёт числа от start до 1.",
        "class Countdown:\n    def __init__(self, start):\n        self.start = start\n\n    def __iter__(self):\n        # Выдай значения протокола итерации\n        return iter([])\n",
        "class Countdown:\n    def __init__(self, start):\n        self.start = start\n\n    def __iter__(self):\n        for value in range(self.start, 0, -1):\n            yield value\n",
        (("list(Countdown(3))", [3, 2, 1]), ("list(Countdown(0))", [])),
        "Метод протокола может сам быть генератором: цикл внутри выдаёт очередное значение.",
        "В __iter__ перебери `range(self.start, 0, -1)` и сделай `yield value`.",
        "__iter__",
        "yield",
    ),
    ("oop-advanced", "special-methods"): _raw(
        "Создай Box(items), для которого встроенная `len(box)` возвращает число элементов.",
        "class Box:\n    def __init__(self, items):\n        self.items = items\n\n    def __len__(self):\n        # Поддержи len(box)\n        return 0\n",
        "class Box:\n    def __init__(self, items):\n        self.items = items\n\n    def __len__(self):\n        return len(self.items)\n",
        (("len(Box([1, 2, 3]))", 3), ("len(Box([]))", 0)),
        "Встроенная len делегирует специальному методу объекта.",
        "В __len__ верни `len(self.items)`.",
        "__len__",
    ),
    # 16. Типы и модели данных
    ("typing-models", "annotations"): _function(
        "def typed_total(values: list[int]) -> int:",
        "Добавь аннотации и реализуй `typed_total(values: list[int]) -> int`.",
        "return sum(values)",
        (("typed_total([1, 2, 3])", 6), ("typed_total([])", 0)),
        "Аннотация параметра стоит после имени, возвращаемого значения — после стрелки.",
        "Заголовок уже размечен; тело — `return sum(values)`.",
        "list[int]",
        "-> int",
    ),
    ("typing-models", "optional-union"): _function(
        "def find_user(users: dict[int, str], user_id: int) -> str | None:",
        "Напиши типизированную `find_user`: верни имя по id либо None.",
        "return users.get(user_id)",
        (("find_user({1: 'Аня'}, 1)", "Аня"), ("find_user({1: 'Аня'}, 2)", None)),
        "Тип `str | None` честно описывает два возможных результата словарного поиска.",
        "Верни `users.get(user_id)`; get без запаса уже возвращает None.",
        "str | None",
    ),
    ("typing-models", "generic-collections"): _function(
        "def add_score(scores: dict[str, int], name: str, score: int) -> dict[str, int]:",
        "Напиши `add_score`: верни копию типизированного словаря с новой оценкой.",
        "updated: dict[str, int] = scores.copy()\nupdated[name] = score\nreturn updated",
        (
            ("add_score({'Аня': 10}, 'Лев', 7)", {"Аня": 10, "Лев": 7}),
            ("add_score({}, 'Аня', 5)", {"Аня": 5}),
        ),
        "Создай копию с аннотацией, затем запиши значение по ключу.",
        "Начни `updated: dict[str, int] = scores.copy()`.",
        "dict[str, int]",
    ),
    ("typing-models", "dataclasses-enums"): _raw(
        "Создай dataclass User с полями name: str и level: int = 1; `user_label` вернёт `name · level`.",
        "from dataclasses import dataclass\n\n@dataclass\nclass User:\n    # Объяви два типизированных поля\n    name: str\n\ndef user_label(name, level=1):\n    user = User(name, level)\n    return f'{user.name} · {user.level}'\n",
        "from dataclasses import dataclass\n\n@dataclass\nclass User:\n    name: str\n    level: int = 1\n\ndef user_label(name, level=1):\n    user = User(name, level)\n    return f'{user.name} · {user.level}'\n",
        (("user_label('Аня')", "Аня · 1"), ("user_label('Лев', 3)", "Лев · 3")),
        "После @dataclass достаточно объявить поля аннотациями; конструктор создастся автоматически.",
        "Добавь строку `level: int = 1` под полем name.",
        "@dataclass",
        "level: int",
    ),
    # 17. Стандартная библиотека I
    ("stdlib-core", "datetime"): _function(
        "def after_days(iso_date, days):",
        "Импортируй date и timedelta: верни ISO-дату через указанное число дней.",
        "start = date.fromisoformat(iso_date)\nreturn (start + timedelta(days=days)).isoformat()",
        (
            ("after_days('2026-01-01', 7)", "2026-01-08"),
            ("after_days('2024-02-28', 1)", "2024-02-29"),
        ),
        "Преобразуй строку в date, прибавь timedelta и снова получи строку.",
        "Используй `date.fromisoformat`, затем `+ timedelta(days=days)`.",
        "timedelta",
        prelude="from datetime import date, timedelta",
    ),
    ("stdlib-core", "random"): _function(
        "def seeded_choice(options, seed):",
        "Напиши воспроизводимый выбор: создай `random.Random(seed)` и вызови choice.",
        "generator = random.Random(seed)\nreturn generator.choice(options)",
        (("seeded_choice(['a', 'b', 'c'], 1)", "a"), ("seeded_choice([10, 20, 30], 5)", 30)),
        "Локальный генератор со seed делает случайный сценарий проверяемым и не меняет глобальное состояние.",
        "Создай `generator = random.Random(seed)` и верни `generator.choice(options)`.",
        "random.Random",
        ".choice(",
        prelude="import random",
    ),
    ("stdlib-core", "math-statistics"): _function(
        "def average(scores):",
        "Импортируй statistics и верни среднее; для пустого списка верни 0.",
        "if not scores:\n    return 0\nreturn statistics.mean(scores)",
        (("average([2, 4, 6])", 4), ("average([])", 0)),
        "До вызова mean обработай пустую коллекцию, для которой среднего нет.",
        "После проверки пустоты верни `statistics.mean(scores)`.",
        "statistics.mean",
        prelude="import statistics",
    ),
    ("stdlib-core", "decimal"): _function(
        "def exact_total(price_text, count):",
        "Импортируй Decimal: умножь цену из строки на количество и верни результат строкой.",
        "price = Decimal(price_text)\nreturn f'{price * count}'",
        (("exact_total('19.90', 3)", "59.70"), ("exact_total('0.10', 3)", "0.30")),
        "Создавай Decimal из строки, чтобы не внести погрешность float.",
        "`price = Decimal(price_text)`, затем верни f-строку с `price * count`.",
        "Decimal(",
        prelude="from decimal import Decimal",
    ),
    # 18. Стандартная библиотека II
    ("stdlib-productivity", "collections"): _function(
        "def word_counts(words):",
        "Импортируй Counter и верни счётчик частот слов.",
        "return Counter(words)",
        (("word_counts(['код', 'тест', 'код'])", {"код": 2, "тест": 1}), ("word_counts([])", {})),
        "Counter принимает iterable и сразу считает повторения; по поведению он сравним со словарём частот.",
        "Верни `Counter(words)`.",
        "Counter(",
        prelude="from collections import Counter",
    ),
    ("stdlib-productivity", "itertools"): _function(
        "def pair_labels(items):",
        "Импортируй combinations и верни подписи всех пар вида `a+b`.",
        "return [f'{left}+{right}' for left, right in combinations(items, 2)]",
        (("pair_labels(['a', 'b', 'c'])", ["a+b", "a+c", "b+c"]), ("pair_labels(['solo'])", [])),
        "combinations(items, 2) выдаёт уникальные пары без перестановок и повторов.",
        "Перебери `for left, right in combinations(items, 2)`.",
        "combinations(",
        prelude="from itertools import combinations",
    ),
    ("stdlib-productivity", "functools"): _raw(
        "Реализуй рекурсивный `fib(n)` под декоратором lru_cache.",
        "from functools import lru_cache\n\n@lru_cache\ndef fib(n):\n    # База: 0 и 1; дальше сумма двух предыдущих\n    return None\n",
        "from functools import lru_cache\n\n@lru_cache\ndef fib(n):\n    if n < 2:\n        return n\n    return fib(n - 1) + fib(n - 2)\n",
        (("fib(0)", 0), ("fib(7)", 13)),
        "Кэш работает поверх обычной корректной рекурсии: сначала база, затем два подызова.",
        "При `n < 2` верни n, иначе `fib(n - 1) + fib(n - 2)`.",
        "@lru_cache",
    ),
    ("stdlib-productivity", "heapq-bisect"): _function(
        "def priority_order(items):",
        "Импортируй heapq: преврати пары `[priority, task]` в кучу и верни задачи по приоритету.",
        "queue = []\nfor priority, task in items:\n    heapq.heappush(queue, (priority, task))\nresult = []\nwhile queue:\n    result.append(heapq.heappop(queue)[1])\nreturn result",
        (
            ("priority_order([[2, 'тесты'], [1, 'код']])", ["код", "тесты"]),
            ("priority_order([])", []),
        ),
        "Добавляй пары в кучу; heappop всегда снимает пару с наименьшим первым элементом.",
        "Используй `heapq.heappush`, затем в while — `heapq.heappop(queue)[1]`.",
        "heapq.heappush",
        "heapq.heappop",
        prelude="import heapq",
    ),
    # 19. Регулярные выражения
    ("regex", "patterns"): _function(
        "def is_iso_date(text):",
        "Импортируй re: проверь полное соответствие шаблону YYYY-MM-DD.",
        "return bool(re.fullmatch(r'\\d{4}-\\d{2}-\\d{2}', text))",
        (("is_iso_date('2026-07-15')", True), ("is_iso_date('15.07.2026')", False)),
        "Сырые строки сохраняют обратные слеши; fullmatch требует совпадения всей строки.",
        "Верни `bool(re.fullmatch(r'\\d{4}-\\d{2}-\\d{2}', text))`.",
        "re.fullmatch",
        "r'",
        prelude="import re",
    ),
    ("regex", "groups"): _function(
        "def parse_metric(text):",
        "Разбери строку `name: 42` именованными группами; верни словарь или None.",
        "match = re.fullmatch(r'(?P<name>\\w+): (?P<value>\\d+)', text)\nif match is None:\n    return None\nreturn {'name': match.group('name'), 'value': int(match.group('value'))}",
        (
            ("parse_metric('score: 42')", {"name": "score", "value": 42}),
            ("parse_metric('wrong')", None),
        ),
        "Сначала проверь match на None, затем доставай группы по именам.",
        "Шаблон содержит `(?P<name>...)` и `(?P<value>...)`; значения бери через group.",
        "?P<name>",
        ".group(",
        prelude="import re",
    ),
    ("regex", "validation"): _function(
        "def valid_postal_code(text):",
        "Верни True только для почтового кода ровно из шести цифр.",
        "return re.fullmatch(r'\\d{6}', text) is not None",
        (
            ("valid_postal_code('123456')", True),
            ("valid_postal_code('12345a')", False),
            ("valid_postal_code('1234567')", False),
        ),
        "Используй fullmatch, а не search, и сравни результат с None.",
        "Проверка: `re.fullmatch(r'\\d{6}', text) is not None`.",
        "re.fullmatch",
        prelude="import re",
    ),
    ("regex", "substitution"): _function(
        "def collapse_spaces(text):",
        "Замени любую последовательность пробельных символов одним обычным пробелом и убери края.",
        "return re.sub(r'\\s+', ' ', text).strip()",
        (
            ("collapse_spaces('  Python   каждый\\nдень ')", "Python каждый день"),
            ("collapse_spaces('код')", "код"),
        ),
        "re.sub получает шаблон, замену и исходный текст; strip отдельно очищает края.",
        "Верни `re.sub(r'\\s+', ' ', text).strip()`.",
        "re.sub",
        prelude="import re",
    ),
    # 20. Тестирование
    ("testing", "unit-tests"): _raw(
        "Реализуй `check_discount`: используй assert для сравнения результата с expected и верни False при провале.",
        "def discount(price):\n    return price * 0.9\n\ndef check_discount(price, expected):\n    # Сделай проверку assert внутри try\n    return None\n",
        "def discount(price):\n    return price * 0.9\n\ndef check_discount(price, expected):\n    try:\n        assert discount(price) == expected\n        return True\n    except Exception:\n        return False\n",
        (("check_discount(100, 90.0)", True), ("check_discount(100, 80.0)", False)),
        "В тесте assert молчит при успехе и выбрасывает ошибку при несовпадении; helper превращает её в bool.",
        "В try напиши `assert discount(price) == expected`, затем True; в except — False.",
        "assert ",
    ),
    ("testing", "fixtures"): _function(
        "def level_up_scenario(make_user):",
        "Напиши сценарий с фабрикой-фикстурой: получи user через make_user, увеличь level и верни его.",
        "user = make_user()\nuser['level'] += 1\nreturn user['level']",
        (
            ("level_up_scenario(lambda: {'level': 1})", 2),
            ("level_up_scenario(lambda: {'level': 4})", 5),
        ),
        "Фикстура подготавливает начальное состояние; тест выполняет действие уже над готовым объектом.",
        "Сначала `user = make_user()`, потом увеличь `user['level']`.",
        "make_user()",
    ),
    ("testing", "parametrize"): _function(
        "def run_cases(function, cases):",
        "Сымитируй параметризацию: для пар `[argument, expected]` верни список результатов сравнений.",
        "return [function(argument) == expected for argument, expected in cases]",
        (
            ("run_cases(lambda value: value * 2, [[1, 2], [3, 6]])", [True, True]),
            ("run_cases(lambda value: value + 1, [[0, 0], [1, 2]])", [False, True]),
        ),
        "Каждый case содержит вход и ожидание; один и тот же function применяется ко всем строкам.",
        "Comprehension сравнивает `function(argument) == expected` для каждой пары.",
        "for argument, expected in cases",
    ),
    ("testing", "mocks"): _raw(
        "Создай FakeClock с методом today(), возвращающим заданную дату; deadline(clock) должен использовать только переданный clock.",
        "class FakeClock:\n    def __init__(self, value):\n        self.value = value\n\n    def today(self):\n        # Верни управляемое время\n        return None\n\ndef deadline(clock):\n    return f'{clock.today()} + 7 дней'\n",
        "class FakeClock:\n    def __init__(self, value):\n        self.value = value\n\n    def today(self):\n        return self.value\n\ndef deadline(clock):\n    return f'{clock.today()} + 7 дней'\n",
        (
            ("deadline(FakeClock('2026-01-01'))", "2026-01-01 + 7 дней"),
            ("deadline(FakeClock('2030-05-10'))", "2030-05-10 + 7 дней"),
        ),
        "Фейк хранит заранее выбранный ответ и тем самым делает тест независимым от реальных часов.",
        "Метод today должен сделать `return self.value`.",
        "class FakeClock",
    ),
    # 21. Качество и Git
    ("quality", "pep8"): _function(
        "def total_score(scores):",
        "Реализуй маленькую функцию с понятными PEP 8-именами: верни сумму scores.",
        "return sum(scores)",
        (("total_score([3, 7])", 10), ("total_score([])", 0)),
        "Хорошее имя описывает данные и не требует комментария; отступ тела — четыре пробела.",
        "Тело читаемой функции здесь — `return sum(scores)`.",
        "total_score",
    ),
    ("quality", "format-lint"): _function(
        "def lint_commands(path):",
        "Напиши `lint_commands(path)`: верни две команды Ruff — форматирование и проверку указанного пути.",
        "return [f'ruff format {path}', f'ruff check {path}']",
        (
            ("lint_commands('app')", ["ruff format app", "ruff check app"]),
            ("lint_commands('tests')", ["ruff format tests", "ruff check tests"]),
        ),
        "Форматтер меняет оформление, линтер ищет проблемы; это два отдельных запуска.",
        "Верни список из f-строк `ruff format ...` и `ruff check ...`.",
        "ruff format",
        "ruff check",
    ),
    ("quality", "docstrings"): _raw(
        "Добавь функции `total(values)` содержательный docstring `Вернуть сумму значений.` и рабочее тело.",
        "def total(values):\n    # На первой строке тела должен быть docstring\n    return 0\n",
        'def total(values):\n    """Вернуть сумму значений."""\n    return sum(values)\n',
        (("total([2, 3])", 5), ("total.__doc__", "Вернуть сумму значений.")),
        "Docstring — строковый литерал сразу после заголовка функции, до исполняемого кода.",
        'Первая строка тела: `"""Вернуть сумму значений."""`, затем sum.',
        "Вернуть сумму значений.",
    ),
    ("quality", "git"): _function(
        "def commit_commands(path, message):",
        "Собери безопасную последовательность Git-команд: status, add одного path, commit с message.",
        """return ["git status", f"git add {path}", f"git commit -m '{message}'"]""",
        (
            (
                "commit_commands('app/service.py', 'Добавить проверку')",
                ["git status", "git add app/service.py", "git commit -m 'Добавить проверку'"],
            ),
            (
                "commit_commands('README.md', 'Обновить docs')",
                ["git status", "git add README.md", "git commit -m 'Обновить docs'"],
            ),
        ),
        "Сначала посмотри состояние, затем индексируй только нужный путь и создай осмысленный commit.",
        "Список начинается `git status`, затем f-строки для add и commit -m.",
        "git status",
        "git add",
        "git commit",
    ),
    # 22. CLI и окружение — безопасные локальные модели без системного доступа
    ("cli-environment", "argv"): _function(
        "def input_argument(args):",
        "Разбери список аргументов через argparse: верни значение `--input` либо None.",
        "parser = argparse.ArgumentParser(add_help=False)\nparser.add_argument('--input')\nreturn parser.parse_args(args).input",
        (("input_argument(['--input', 'data.csv'])", "data.csv"), ("input_argument([])", None)),
        "Создай parser, объяви один необязательный аргумент и разбери именно переданный список.",
        "Используй `ArgumentParser(add_help=False)`, `add_argument('--input')` и `parse_args(args).input`.",
        "argparse.ArgumentParser",
        ".add_argument(",
        ".parse_args(",
        prelude="import argparse",
    ),
    ("cli-environment", "environment"): _function(
        "def api_url(env):",
        "Без доступа к ОС прочитай настройку из переданного env-словаря; запас — `http://localhost`.",
        "return env.get('API_URL', 'http://localhost')",
        (
            ("api_url({'API_URL': 'https://example.test'})", "https://example.test"),
            ("api_url({})", "http://localhost"),
        ),
        "Переменная окружения моделируется словарём, поэтому подходит get с запасным значением.",
        "Верни `env.get('API_URL', 'http://localhost')`.",
        "API_URL",
    ),
    ("cli-environment", "venv"): _function(
        "def activation_command(platform):",
        "Верни команду активации venv: Windows → `.venv\\Scripts\\activate`, иначе `source .venv/bin/activate`.",
        "if platform == 'windows':\n    return '.venv\\\\Scripts\\\\activate'\nreturn 'source .venv/bin/activate'",
        (
            ("activation_command('windows')", ".venv\\Scripts\\activate"),
            ("activation_command('linux')", "source .venv/bin/activate"),
        ),
        "Путь активации зависит от оболочки, поэтому раздели два сценария условием.",
        "Для windows верни строку с экранированными обратными слешами, иначе source-путь.",
        ".venv",
    ),
    ("cli-environment", "pyproject"): _function(
        "def project_name(config):",
        "Прочитай имя из модели pyproject-словаря `config['project']['name']`, а при отсутствии верни `unknown`.",
        "return config.get('project', {}).get('name', 'unknown')",
        (
            ("project_name({'project': {'name': 'my-app'}})", "my-app"),
            ("project_name({})", "unknown"),
        ),
        "TOML после разбора становится вложенными словарями; безопасно пройди два уровня через get.",
        "Цепочка: `config.get('project', {}).get('name', 'unknown')`.",
        "project",
        "name",
    ),
    # 23. HTTP и API — чистые функции над запросами и ответами
    ("http-api", "request-response"): _function(
        "def request_line(method, path):",
        "Собери первую строку HTTP-запроса вида `GET /api/tasks HTTP/1.1`.",
        "return f'{method.upper()} {path} HTTP/1.1'",
        (
            ("request_line('get', '/api/tasks')", "GET /api/tasks HTTP/1.1"),
            ("request_line('post', '/items')", "POST /items HTTP/1.1"),
        ),
        "Метод принято писать верхним регистром; путь и версия разделяются пробелами.",
        "Верни f-строку из `method.upper()`, path и `HTTP/1.1`.",
        "HTTP/1.1",
    ),
    ("http-api", "json-api"): _function(
        "def task_payload(title, done=False):",
        "Подготовь JSON-совместимый словарь задачи с полями title и done.",
        "return {'title': title, 'done': done}",
        (
            ("task_payload('Купить молоко')", {"title": "Купить молоко", "done": False}),
            ("task_payload('Код', True)", {"title": "Код", "done": True}),
        ),
        "JSON-объект в Python моделируется словарём, а false — значением False.",
        "Верни `{'title': title, 'done': done}`.",
        "title",
        "done",
    ),
    ("http-api", "status-codes"): _function(
        "def status_group(code):",
        "Классифицируй HTTP-код: 2xx → success, 4xx → client_error, 5xx → server_error, иначе other.",
        "if 200 <= code < 300:\n    return 'success'\nif 400 <= code < 500:\n    return 'client_error'\nif 500 <= code < 600:\n    return 'server_error'\nreturn 'other'",
        (
            ("status_group(200)", "success"),
            ("status_group(404)", "client_error"),
            ("status_group(503)", "server_error"),
        ),
        "Категорию задаёт первая цифра; используй полуинтервалы, чтобы не перечислять коды.",
        "Проверь диапазоны `200 <= code < 300`, затем 400 и 500.",
        "200",
        "400",
        "500",
    ),
    ("http-api", "pagination"): _function(
        "def page(items, limit, offset):",
        "Реализуй локальную пагинацию: верни limit элементов, начиная с offset.",
        "return items[offset:offset + limit]",
        (("page(list(range(10)), 3, 2)", [2, 3, 4]), ("page(['a', 'b'], 5, 1)", ["b"])),
        "offset — начало среза, конец получается сложением offset и limit.",
        "Верни `items[offset:offset + limit]`.",
        "offset",
        "limit",
    ),
    # 24. Базы данных — SQL-контракты и атомарная модель без внешней БД
    ("databases", "relational"): _function(
        "def row_to_task(row):",
        "Преобразуй строку таблицы `[id, title, done]` в словарь с теми же полями.",
        "task_id, title, done = row\nreturn {'id': task_id, 'title': title, 'done': bool(done)}",
        (
            ("row_to_task([1, 'Код', 0])", {"id": 1, "title": "Код", "done": False}),
            ("row_to_task([2, 'Тесты', 1])", {"id": 2, "title": "Тесты", "done": True}),
        ),
        "Сначала распакуй столбцы в имена; первичный ключ id сохраняется без изменений.",
        "Сделай `task_id, title, done = row`, затем собери словарь.",
        "task_id",
    ),
    ("databases", "crud"): _function(
        "def task_query(done):",
        "Собери SELECT для чтения задач: условие done должно быть 1 или 0.",
        "flag = int(done)\nreturn f'SELECT id, title FROM tasks WHERE done = {flag}'",
        (
            ("task_query(False)", "SELECT id, title FROM tasks WHERE done = 0"),
            ("task_query(True)", "SELECT id, title FROM tasks WHERE done = 1"),
        ),
        "SELECT читает столбцы, FROM задаёт таблицу, WHERE фильтрует строки.",
        "Преобразуй bool в 1/0 и подставь в `SELECT id, title FROM tasks WHERE done = ...`.",
        "SELECT",
        "WHERE",
    ),
    ("databases", "parameters"): _function(
        "def select_by_id(task_id):",
        "Создай учебную SQLite-базу в памяти и найди title по id параметризованным запросом; если строки нет, верни None.",
        'with sqlite3.connect(\':memory:\') as connection:\n    connection.execute(\'CREATE TABLE tasks (id INTEGER PRIMARY KEY, title TEXT)\')\n    connection.execute("INSERT INTO tasks VALUES (?, ?)", (1, "Код"))\n    connection.execute("INSERT INTO tasks VALUES (?, ?)", (2, "Тесты"))\n    row = connection.execute(\'SELECT title FROM tasks WHERE id = ?\', (task_id,)).fetchone()\nif row is None:\n    return None\nreturn row[0]',
        (("select_by_id(1)", "Код"), ("select_by_id(9)", None)),
        "Соединение живёт только внутри with; значение task_id передаётся отдельным одноэлементным кортежем.",
        "В SELECT оставь `?`, а вторым аргументом execute передай `(task_id,)`; затем обработай fetchone().",
        "sqlite3.connect",
        "?",
        "(task_id,)",
        prelude="import sqlite3",
    ),
    ("databases", "transactions"): _function(
        "def transfer(balances, sender, receiver, amount):",
        "Сымитируй транзакцию: работай с копией; при нехватке денег верни исходные балансы без частичного изменения.",
        "updated = balances.copy()\nif amount < 0 or updated.get(sender, 0) < amount:\n    return balances.copy()\nupdated[sender] -= amount\nupdated[receiver] = updated.get(receiver, 0) + amount\nreturn updated",
        (
            ("transfer({'A': 10, 'B': 2}, 'A', 'B', 4)", {"A": 6, "B": 6}),
            ("transfer({'A': 1, 'B': 2}, 'A', 'B', 4)", {"A": 1, "B": 2}),
        ),
        "Атомарность означает: сначала проверь все условия на копии, только затем применяй обе записи.",
        "Создай `updated = balances.copy()`; при ошибке верни неизменённую копию, иначе измени обе стороны.",
        "copy()",
    ),
    # 25. Параллельность — безопасные детерминированные модели
    ("concurrency", "threads-processes"): _function(
        "def worker_kind(task_kind):",
        "Выбери модель: `io` → threads, `cpu` → processes, неизвестное → sequential.",
        "if task_kind == 'io':\n    return 'threads'\nif task_kind == 'cpu':\n    return 'processes'\nreturn 'sequential'",
        (
            ("worker_kind('io')", "threads"),
            ("worker_kind('cpu')", "processes"),
            ("worker_kind('other')", "sequential"),
        ),
        "Потоки подходят ожиданию I/O, процессы — вычислительной CPU-нагрузке.",
        "Раздели `io` и `cpu` двумя ветками, затем верни sequential.",
        "threads",
        "processes",
    ),
    ("concurrency", "thread-pool"): _function(
        "def pool_map(mapper, items):",
        "Примени mapper ко всем items через безопасный ThreadPoolExecutor из двух потоков.",
        "with ThreadPoolExecutor(max_workers=2) as pool:\n    return list(pool.map(mapper, items))",
        (
            ("pool_map(lambda value: value * 2, [1, 2, 3])", [2, 4, 6]),
            ("pool_map(str.upper, ['a', 'b'])", ["A", "B"]),
        ),
        "Создай пул контекстным менеджером: после выхода потоки гарантированно завершаются.",
        "Внутри `with ThreadPoolExecutor(max_workers=2) as pool` верни `list(pool.map(...))`.",
        "ThreadPoolExecutor",
        "pool.map(",
        prelude="from concurrent.futures import ThreadPoolExecutor",
    ),
    ("concurrency", "locks"): _function(
        "def apply_updates(balance, updates):",
        "Защити обновление баланса настоящим Lock и верни результат после всех изменений.",
        "lock = Lock()\ncurrent = balance\nfor amount in updates:\n    with lock:\n        current += amount\nreturn current",
        (("apply_updates(100, [10, -5, 2])", 107), ("apply_updates(0, [])", 0)),
        "Lock создаётся один раз; контекстный менеджер делает чтение и запись критической секцией.",
        "Создай `lock = Lock()` и помести `current += amount` внутрь `with lock`.",
        "Lock(",
        "with lock",
        "current += amount",
        prelude="from threading import Lock",
    ),
    ("concurrency", "queues"): _function(
        "def process_queue(jobs):",
        "Обработай jobs настоящей FIFO Queue: сначала put всех заданий, затем get до опустошения.",
        "queue = Queue()\nfor job in jobs:\n    queue.put(job)\nprocessed = []\nwhile not queue.empty():\n    processed.append(queue.get())\nreturn processed",
        (("process_queue(['a', 'b', 'c'])", ["a", "b", "c"]), ("process_queue([])", [])),
        "Queue хранит потокобезопасный FIFO-контракт: put добавляет, get снимает первый элемент.",
        "Создай `Queue()`, заполни через put и переноси `queue.get()` пока очередь не empty.",
        "Queue(",
        ".put(",
        ".get(",
        prelude="from queue import Queue",
    ),
    # 26. Асинхронный Python
    ("async", "coroutines"): _raw(
        "Напиши async-функцию `fetch(value)`: уступи управление через `await asyncio.sleep(0)` и верни value * 2.",
        "import asyncio\n\nasync def fetch(value):\n    # Уступи управление циклу событий\n    return None\n",
        "import asyncio\n\nasync def fetch(value):\n    await asyncio.sleep(0)\n    return value * 2\n",
        (("asyncio.run(fetch(3))", 6), ("asyncio.run(fetch(0))", 0)),
        "await можно писать внутри async def; sleep(0) безопасно передаёт управление другим задачам.",
        "Внутри fetch: `await asyncio.sleep(0)`, затем `return value * 2`.",
        "async def",
        "await",
    ),
    ("async", "tasks"): _raw(
        "Реализуй `run_pair(left, right)`: создай две asyncio-задачи для готовой double и дождись обеих.",
        "import asyncio\n\nasync def double(value):\n    await asyncio.sleep(0)\n    return value * 2\n\nasync def run_pair(left, right):\n    # Создай две задачи и дождись результатов\n    return None\n",
        "import asyncio\n\nasync def double(value):\n    await asyncio.sleep(0)\n    return value * 2\n\nasync def run_pair(left, right):\n    first = asyncio.create_task(double(left))\n    second = asyncio.create_task(double(right))\n    return [await first, await second]\n",
        (("asyncio.run(run_pair(2, 5))", [4, 10]), ("asyncio.run(run_pair(0, 1))", [0, 2])),
        "create_task планирует coroutine; результат каждой Task получают через await.",
        "Создай first/second через `asyncio.create_task`, затем верни `[await first, await second]`.",
        "asyncio.create_task",
    ),
    ("async", "gather-timeouts"): _raw(
        "Напиши `gather_squares(values)`: передай корутины square в asyncio.gather и верни список результатов.",
        "import asyncio\n\nasync def square(value):\n    await asyncio.sleep(0)\n    return value * value\n\nasync def gather_squares(values):\n    # Собери корутины одним gather\n    return None\n",
        "import asyncio\n\nasync def square(value):\n    await asyncio.sleep(0)\n    return value * value\n\nasync def gather_squares(values):\n    results = await asyncio.gather(*(square(value) for value in values))\n    return list(results)\n",
        (("asyncio.run(gather_squares([2, 3]))", [4, 9]), ("asyncio.run(gather_squares([]))", [])),
        "Распакуй генератор корутин звёздочкой; один await ждёт всю группу.",
        "Используй `await asyncio.gather(*(square(value) for value in values))`.",
        "asyncio.gather",
    ),
    ("async", "async-design"): _raw(
        "Напиши отзывчивую coroutine `polite_total(values)`: суммируй значения и на каждой итерации делай await sleep(0).",
        "import asyncio\n\nasync def polite_total(values):\n    total = 0\n    for value in values:\n        # Уступи управление и обнови total\n        return None\n",
        "import asyncio\n\nasync def polite_total(values):\n    total = 0\n    for value in values:\n        await asyncio.sleep(0)\n        total += value\n    return total\n",
        (("asyncio.run(polite_total([1, 2, 3]))", 6), ("asyncio.run(polite_total([]))", 0)),
        "Долгий цикл должен периодически отдавать управление; итог возвращается только после цикла.",
        "В цикле поставь `await asyncio.sleep(0)` и `total += value`; return — ниже цикла.",
        "await asyncio.sleep",
    ),
    # 27. Выпускные проекты — маленькие проверяемые ядра
    ("capstones", "task-manager"): _function(
        "def toggle_task(task):",
        "Реализуй ядро менеджера задач: верни копию task с инвертированным полем done.",
        "updated = task.copy()\nupdated['done'] = not updated.get('done', False)\nreturn updated",
        (
            ("toggle_task({'title': 'Код', 'done': False})", {"title": "Код", "done": True}),
            ("toggle_task({'title': 'Тесты', 'done': True})", {"title": "Тесты", "done": False}),
        ),
        "Не меняй входной словарь проекта: сначала сделай копию, затем переключи состояние.",
        "Создай updated через copy и присвой `not updated.get('done', False)`.",
        "done",
    ),
    ("capstones", "notes-app"): _function(
        "def notes_roundtrip(notes):",
        "Реализуй ядро хранения заметок: JSON-сериализация UTF-8 и обратное восстановление.",
        "payload = json.dumps(notes, ensure_ascii=False)\nreturn json.loads(payload)",
        (
            (
                "notes_roundtrip([{'title': 'Идея', 'text': 'Курс'}])",
                [{"title": "Идея", "text": "Курс"}],
            ),
            ("notes_roundtrip([])", []),
        ),
        "Граница хранения принимает текст; проверь обе стороны контракта dumps/loads.",
        "Сначала `json.dumps(..., ensure_ascii=False)`, затем `json.loads(payload)`.",
        "json.dumps",
        "json.loads",
        prelude="import json",
    ),
    ("capstones", "api-client"): _function(
        "def weather_result(status, payload):",
        "Реализуй ядро API-клиента: для 200 верни температуру, иначе строку `Ошибка <status>`.",
        "if status != 200:\n    return f'Ошибка {status}'\nreturn payload.get('temperature')",
        (
            ("weather_result(200, {'temperature': 21})", 21),
            ("weather_result(404, {})", "Ошибка 404"),
        ),
        "Сначала разберите транспортный статус; только при успехе читайте контракт JSON.",
        "При status != 200 верни ошибку, иначе `payload.get('temperature')`.",
        "status",
        "payload",
    ),
    ("capstones", "release"): _function(
        "def missing_release_files(files):",
        "Проверь релиз: верни в стандартном порядке обязательные файлы, которых нет.",
        "required = ['src', 'tests', 'pyproject.toml', 'README.md']\nreturn [name for name in required if name not in files]",
        (
            ("missing_release_files(['src', 'tests', 'pyproject.toml', 'README.md'])", []),
            ("missing_release_files(['src', 'README.md'])", ["tests", "pyproject.toml"]),
        ),
        "Список required — контракт релиза; comprehension сравнивает его с фактическим набором.",
        "Создай required из четырёх имён и отфильтруй отсутствующие через `if name not in files`.",
        "README.md",
        "pyproject.toml",
    ),
}


def topical_task_blueprint(module_id: str, slug: str) -> TaskBlueprint:
    """Вернуть внутреннюю спецификацию; используется только проверками курса."""
    return TOPICAL_TASKS[(module_id, slug)]


def build_topical_code_task(
    module_id: str,
    lesson_spec: tuple[str, str, str, str, str, str, str],
) -> dict[str, Any]:
    """Собрать публичную code-задачу с тематическими опорами без готового ответа."""
    slug, title, subtitle, keyword, example, concept, _ = lesson_spec
    blueprint = topical_task_blueprint(module_id, slug)
    signature = next((line.strip() for line in example.splitlines() if line.strip()), keyword)
    return {
        "prompt": f"Тематическая практика «{title}». {blueprint.prompt}",
        "starter": blueprint.starter,
        "tests": [
            *(
                {"kind": "call", "call": call, "expected": expected}
                for call, expected in blueprint.cases
            ),
            {
                "kind": "source",
                "required_tokens": list(blueprint.required_tokens),
                "expected": True,
            },
        ],
        "explanation": (
            f"Задача проверяет именно тему «{title}»: {concept} "
            "Попробуй придумать ещё один вход и предсказать результат без запуска."
        ),
        "guide": f"Тема: {keyword}. {blueprint.plan}",
        "hint": blueprint.near_solution,
        "hints": [
            "Сначала назови входные данные и требуемый результат своими словами. "
            "Затем выбери одно действие, которое превращает первое во второе.",
            f"Нужный инструмент — «{keyword}». {concept}",
            f"План решения: {blueprint.plan}",
            f"Почти решение: {blueprint.near_solution}",
        ],
        "tool_help": [
            {
                "name": keyword,
                "kind": "Инструмент текущего урока",
                "signature": signature,
                "description": f"{concept} {subtitle}.",
                "example": example,
                "language": (
                    "shell"
                    if module_id == "quality" and slug in {"format-lint", "git"}
                    else "python"
                ),
            }
        ],
        "purpose": "topical_application",
        "focus_concepts": [keyword],
        "review_concepts": [],
        "mandatory": True,
        "required_tokens": list(blueprint.required_tokens),
        "reference_solution": blueprint.solution,
    }
